###

エラー出てるけど動いてそう

```
(base) chino@chino-Legion-5-15IAH7H:~/JetsonWorks_250117/GachaconSensorDispaly/for_systemd$ python test_paramiko_cansend_mode_standby.py 
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_9.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
192.168.0.101に接続しました。
コマンド出力:
エラー出力:
Exception ignored in: <function BufferedFile.__del__ at 0x7ff22eb81580>
Traceback (most recent call last):
  File "/home/chino/anaconda3/lib/python3.12/site-packages/paramiko/file.py", line 67, in __del__
  File "/home/chino/anaconda3/lib/python3.12/site-packages/paramiko/channel.py", line 1390, in close
  File "/home/chino/anaconda3/lib/python3.12/site-packages/paramiko/channel.py", line 989, in shutdown_write
  File "/home/chino/anaconda3/lib/python3.12/site-packages/paramiko/channel.py", line 965, in shutdown
  File "/home/chino/anaconda3/lib/python3.12/site-packages/paramiko/transport.py", line 1971, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
(base) chino@chino-Legion-5-15IAH7H:~/JetsonWorks_250117/GachaconSensorDispaly/for_systemd$ 
```